// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ECSSE.proto
// Original file comments:
//
// Created by helen chan  on 06/11/2021
// Email: kaibaking@gmail.com
// 
#ifndef GRPC_ECSSE_2eproto__INCLUDED
#define GRPC_ECSSE_2eproto__INCLUDED

#include "ECSSE.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ECSSE {

class RPC final {
 public:
  static constexpr char const* service_full_name() {
    return "ECSSE.RPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Setup
    virtual ::grpc::Status setup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::ECSSE::ExecuteStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>> Asyncsetup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>>(AsyncsetupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>> PrepareAsyncsetup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>>(PrepareAsyncsetupRaw(context, request, cq));
    }
    // Search
    std::unique_ptr< ::grpc::ClientReaderInterface< ::ECSSE::SearchReply>> search(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::ECSSE::SearchReply>>(searchRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ECSSE::SearchReply>> Asyncsearch(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ECSSE::SearchReply>>(AsyncsearchRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ECSSE::SearchReply>> PrepareAsyncsearch(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ECSSE::SearchReply>>(PrepareAsyncsearchRaw(context, request, cq));
    }
    // Update
    virtual ::grpc::Status update(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::ECSSE::ExecuteStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>> Asyncupdate(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>>(AsyncupdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>> PrepareAsyncupdate(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>>(PrepareAsyncupdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::ECSSE::UpdateRequestMessage>> batch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::ECSSE::UpdateRequestMessage>>(batch_updateRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::UpdateRequestMessage>> Asyncbatch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::UpdateRequestMessage>>(Asyncbatch_updateRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::UpdateRequestMessage>> PrepareAsyncbatch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::UpdateRequestMessage>>(PrepareAsyncbatch_updateRaw(context, response, cq));
    }
    // only used for expriment simulation
    virtual ::grpc::Status cache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::ECSSE::ExecuteStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>> Asynccache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>>(AsynccacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>> PrepareAsynccache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>>(PrepareAsynccacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::ECSSE::CacheRequestMessage>> batch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::ECSSE::CacheRequestMessage>>(batch_cacheRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::CacheRequestMessage>> Asyncbatch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::CacheRequestMessage>>(Asyncbatch_cacheRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::CacheRequestMessage>> PrepareAsyncbatch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::ECSSE::CacheRequestMessage>>(PrepareAsyncbatch_cacheRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Setup
      virtual void setup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage* request, ::ECSSE::ExecuteStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void setup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage* request, ::ECSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Search
      virtual void search(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage* request, ::grpc::ClientReadReactor< ::ECSSE::SearchReply>* reactor) = 0;
      // Update
      virtual void update(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage* request, ::ECSSE::ExecuteStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void update(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage* request, ::ECSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void batch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::ECSSE::UpdateRequestMessage>* reactor) = 0;
      // only used for expriment simulation
      virtual void cache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage* request, ::ECSSE::ExecuteStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void cache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage* request, ::ECSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void batch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::ECSSE::CacheRequestMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>* AsyncsetupRaw(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>* PrepareAsyncsetupRaw(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::ECSSE::SearchReply>* searchRaw(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ECSSE::SearchReply>* AsyncsearchRaw(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ECSSE::SearchReply>* PrepareAsyncsearchRaw(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>* AsyncupdateRaw(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>* PrepareAsyncupdateRaw(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::ECSSE::UpdateRequestMessage>* batch_updateRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::ECSSE::UpdateRequestMessage>* Asyncbatch_updateRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::ECSSE::UpdateRequestMessage>* PrepareAsyncbatch_updateRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>* AsynccacheRaw(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ECSSE::ExecuteStatus>* PrepareAsynccacheRaw(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::ECSSE::CacheRequestMessage>* batch_cacheRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::ECSSE::CacheRequestMessage>* Asyncbatch_cacheRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::ECSSE::CacheRequestMessage>* PrepareAsyncbatch_cacheRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status setup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::ECSSE::ExecuteStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>> Asyncsetup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>>(AsyncsetupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>> PrepareAsyncsetup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>>(PrepareAsyncsetupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::ECSSE::SearchReply>> search(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::ECSSE::SearchReply>>(searchRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ECSSE::SearchReply>> Asyncsearch(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ECSSE::SearchReply>>(AsyncsearchRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ECSSE::SearchReply>> PrepareAsyncsearch(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ECSSE::SearchReply>>(PrepareAsyncsearchRaw(context, request, cq));
    }
    ::grpc::Status update(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::ECSSE::ExecuteStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>> Asyncupdate(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>>(AsyncupdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>> PrepareAsyncupdate(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>>(PrepareAsyncupdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::ECSSE::UpdateRequestMessage>> batch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::ECSSE::UpdateRequestMessage>>(batch_updateRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::UpdateRequestMessage>> Asyncbatch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::UpdateRequestMessage>>(Asyncbatch_updateRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::UpdateRequestMessage>> PrepareAsyncbatch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::UpdateRequestMessage>>(PrepareAsyncbatch_updateRaw(context, response, cq));
    }
    ::grpc::Status cache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::ECSSE::ExecuteStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>> Asynccache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>>(AsynccacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>> PrepareAsynccache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>>(PrepareAsynccacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::ECSSE::CacheRequestMessage>> batch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::ECSSE::CacheRequestMessage>>(batch_cacheRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::CacheRequestMessage>> Asyncbatch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::CacheRequestMessage>>(Asyncbatch_cacheRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::CacheRequestMessage>> PrepareAsyncbatch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::ECSSE::CacheRequestMessage>>(PrepareAsyncbatch_cacheRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void setup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage* request, ::ECSSE::ExecuteStatus* response, std::function<void(::grpc::Status)>) override;
      void setup(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage* request, ::ECSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void search(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage* request, ::grpc::ClientReadReactor< ::ECSSE::SearchReply>* reactor) override;
      void update(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage* request, ::ECSSE::ExecuteStatus* response, std::function<void(::grpc::Status)>) override;
      void update(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage* request, ::ECSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void batch_update(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::ECSSE::UpdateRequestMessage>* reactor) override;
      void cache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage* request, ::ECSSE::ExecuteStatus* response, std::function<void(::grpc::Status)>) override;
      void cache(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage* request, ::ECSSE::ExecuteStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void batch_cache(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::ECSSE::CacheRequestMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>* AsyncsetupRaw(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>* PrepareAsyncsetupRaw(::grpc::ClientContext* context, const ::ECSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::ECSSE::SearchReply>* searchRaw(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request) override;
    ::grpc::ClientAsyncReader< ::ECSSE::SearchReply>* AsyncsearchRaw(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::ECSSE::SearchReply>* PrepareAsyncsearchRaw(::grpc::ClientContext* context, const ::ECSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>* AsyncupdateRaw(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>* PrepareAsyncupdateRaw(::grpc::ClientContext* context, const ::ECSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::ECSSE::UpdateRequestMessage>* batch_updateRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) override;
    ::grpc::ClientAsyncWriter< ::ECSSE::UpdateRequestMessage>* Asyncbatch_updateRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::ECSSE::UpdateRequestMessage>* PrepareAsyncbatch_updateRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>* AsynccacheRaw(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ECSSE::ExecuteStatus>* PrepareAsynccacheRaw(::grpc::ClientContext* context, const ::ECSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::ECSSE::CacheRequestMessage>* batch_cacheRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response) override;
    ::grpc::ClientAsyncWriter< ::ECSSE::CacheRequestMessage>* Asyncbatch_cacheRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::ECSSE::CacheRequestMessage>* PrepareAsyncbatch_cacheRaw(::grpc::ClientContext* context, ::ECSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_setup_;
    const ::grpc::internal::RpcMethod rpcmethod_search_;
    const ::grpc::internal::RpcMethod rpcmethod_update_;
    const ::grpc::internal::RpcMethod rpcmethod_batch_update_;
    const ::grpc::internal::RpcMethod rpcmethod_cache_;
    const ::grpc::internal::RpcMethod rpcmethod_batch_cache_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Setup
    virtual ::grpc::Status setup(::grpc::ServerContext* context, const ::ECSSE::SetupRequestMessage* request, ::ECSSE::ExecuteStatus* response);
    // Search
    virtual ::grpc::Status search(::grpc::ServerContext* context, const ::ECSSE::SearchRequestMessage* request, ::grpc::ServerWriter< ::ECSSE::SearchReply>* writer);
    // Update
    virtual ::grpc::Status update(::grpc::ServerContext* context, const ::ECSSE::UpdateRequestMessage* request, ::ECSSE::ExecuteStatus* response);
    virtual ::grpc::Status batch_update(::grpc::ServerContext* context, ::grpc::ServerReader< ::ECSSE::UpdateRequestMessage>* reader, ::ECSSE::ExecuteStatus* response);
    // only used for expriment simulation
    virtual ::grpc::Status cache(::grpc::ServerContext* context, const ::ECSSE::CacheRequestMessage* request, ::ECSSE::ExecuteStatus* response);
    virtual ::grpc::Status batch_cache(::grpc::ServerContext* context, ::grpc::ServerReader< ::ECSSE::CacheRequestMessage>* reader, ::ECSSE::ExecuteStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setup() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::ECSSE::SetupRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsetup(::grpc::ServerContext* context, ::ECSSE::SetupRequestMessage* request, ::grpc::ServerAsyncResponseWriter< ::ECSSE::ExecuteStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_search() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* /*context*/, const ::ECSSE::SearchRequestMessage* /*request*/, ::grpc::ServerWriter< ::ECSSE::SearchReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsearch(::grpc::ServerContext* context, ::ECSSE::SearchRequestMessage* request, ::grpc::ServerAsyncWriter< ::ECSSE::SearchReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_update() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update(::grpc::ServerContext* /*context*/, const ::ECSSE::UpdateRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestupdate(::grpc::ServerContext* context, ::ECSSE::UpdateRequestMessage* request, ::grpc::ServerAsyncResponseWriter< ::ECSSE::ExecuteStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_batch_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_batch_update() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_batch_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_update(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::UpdateRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_update(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::ECSSE::ExecuteStatus, ::ECSSE::UpdateRequestMessage>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(3, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_cache() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cache(::grpc::ServerContext* /*context*/, const ::ECSSE::CacheRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcache(::grpc::ServerContext* context, ::ECSSE::CacheRequestMessage* request, ::grpc::ServerAsyncResponseWriter< ::ECSSE::ExecuteStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_batch_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_batch_cache() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_batch_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_cache(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::CacheRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_cache(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::ECSSE::ExecuteStatus, ::ECSSE::CacheRequestMessage>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(5, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_setup<WithAsyncMethod_search<WithAsyncMethod_update<WithAsyncMethod_batch_update<WithAsyncMethod_cache<WithAsyncMethod_batch_cache<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_setup() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ECSSE::SetupRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ECSSE::SetupRequestMessage* request, ::ECSSE::ExecuteStatus* response) { return this->setup(context, request, response); }));}
    void SetMessageAllocatorFor_setup(
        ::grpc::MessageAllocator< ::ECSSE::SetupRequestMessage, ::ECSSE::ExecuteStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ECSSE::SetupRequestMessage, ::ECSSE::ExecuteStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::ECSSE::SetupRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setup(
      ::grpc::CallbackServerContext* /*context*/, const ::ECSSE::SetupRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_search() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::ECSSE::SearchRequestMessage, ::ECSSE::SearchReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ECSSE::SearchRequestMessage* request) { return this->search(context, request); }));
    }
    ~WithCallbackMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* /*context*/, const ::ECSSE::SearchRequestMessage* /*request*/, ::grpc::ServerWriter< ::ECSSE::SearchReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::ECSSE::SearchReply>* search(
      ::grpc::CallbackServerContext* /*context*/, const ::ECSSE::SearchRequestMessage* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_update() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::ECSSE::UpdateRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ECSSE::UpdateRequestMessage* request, ::ECSSE::ExecuteStatus* response) { return this->update(context, request, response); }));}
    void SetMessageAllocatorFor_update(
        ::grpc::MessageAllocator< ::ECSSE::UpdateRequestMessage, ::ECSSE::ExecuteStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ECSSE::UpdateRequestMessage, ::ECSSE::ExecuteStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update(::grpc::ServerContext* /*context*/, const ::ECSSE::UpdateRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* update(
      ::grpc::CallbackServerContext* /*context*/, const ::ECSSE::UpdateRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_batch_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_batch_update() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackClientStreamingHandler< ::ECSSE::UpdateRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, ::ECSSE::ExecuteStatus* response) { return this->batch_update(context, response); }));
    }
    ~WithCallbackMethod_batch_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_update(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::UpdateRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::ECSSE::UpdateRequestMessage>* batch_update(
      ::grpc::CallbackServerContext* /*context*/, ::ECSSE::ExecuteStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_cache() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::ECSSE::CacheRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ECSSE::CacheRequestMessage* request, ::ECSSE::ExecuteStatus* response) { return this->cache(context, request, response); }));}
    void SetMessageAllocatorFor_cache(
        ::grpc::MessageAllocator< ::ECSSE::CacheRequestMessage, ::ECSSE::ExecuteStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ECSSE::CacheRequestMessage, ::ECSSE::ExecuteStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cache(::grpc::ServerContext* /*context*/, const ::ECSSE::CacheRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* cache(
      ::grpc::CallbackServerContext* /*context*/, const ::ECSSE::CacheRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_batch_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_batch_cache() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackClientStreamingHandler< ::ECSSE::CacheRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, ::ECSSE::ExecuteStatus* response) { return this->batch_cache(context, response); }));
    }
    ~WithCallbackMethod_batch_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_cache(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::CacheRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::ECSSE::CacheRequestMessage>* batch_cache(
      ::grpc::CallbackServerContext* /*context*/, ::ECSSE::ExecuteStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_setup<WithCallbackMethod_search<WithCallbackMethod_update<WithCallbackMethod_batch_update<WithCallbackMethod_cache<WithCallbackMethod_batch_cache<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setup() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::ECSSE::SetupRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_search() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* /*context*/, const ::ECSSE::SearchRequestMessage* /*request*/, ::grpc::ServerWriter< ::ECSSE::SearchReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_update() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update(::grpc::ServerContext* /*context*/, const ::ECSSE::UpdateRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_batch_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_batch_update() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_batch_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_update(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::UpdateRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_cache() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cache(::grpc::ServerContext* /*context*/, const ::ECSSE::CacheRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_batch_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_batch_cache() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_batch_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_cache(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::CacheRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setup() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::ECSSE::SetupRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsetup(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_search() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* /*context*/, const ::ECSSE::SearchRequestMessage* /*request*/, ::grpc::ServerWriter< ::ECSSE::SearchReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsearch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_update() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update(::grpc::ServerContext* /*context*/, const ::ECSSE::UpdateRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestupdate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_batch_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_batch_update() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_batch_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_update(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::UpdateRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_update(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(3, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_cache() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cache(::grpc::ServerContext* /*context*/, const ::ECSSE::CacheRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcache(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_batch_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_batch_cache() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_batch_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_cache(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::CacheRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_cache(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(5, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_setup() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setup(context, request, response); }));
    }
    ~WithRawCallbackMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::ECSSE::SetupRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setup(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_search() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->search(context, request); }));
    }
    ~WithRawCallbackMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* /*context*/, const ::ECSSE::SearchRequestMessage* /*request*/, ::grpc::ServerWriter< ::ECSSE::SearchReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* search(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_update() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->update(context, request, response); }));
    }
    ~WithRawCallbackMethod_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update(::grpc::ServerContext* /*context*/, const ::ECSSE::UpdateRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* update(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_batch_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_batch_update() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->batch_update(context, response); }));
    }
    ~WithRawCallbackMethod_batch_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_update(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::UpdateRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* batch_update(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_cache() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->cache(context, request, response); }));
    }
    ~WithRawCallbackMethod_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cache(::grpc::ServerContext* /*context*/, const ::ECSSE::CacheRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* cache(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_batch_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_batch_cache() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->batch_cache(context, response); }));
    }
    ~WithRawCallbackMethod_batch_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_cache(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::ECSSE::CacheRequestMessage>* /*reader*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* batch_cache(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setup() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ECSSE::SetupRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ECSSE::SetupRequestMessage, ::ECSSE::ExecuteStatus>* streamer) {
                       return this->Streamedsetup(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::ECSSE::SetupRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsetup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ECSSE::SetupRequestMessage,::ECSSE::ExecuteStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_update : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_update() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ECSSE::UpdateRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ECSSE::UpdateRequestMessage, ::ECSSE::ExecuteStatus>* streamer) {
                       return this->Streamedupdate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_update() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status update(::grpc::ServerContext* /*context*/, const ::ECSSE::UpdateRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedupdate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ECSSE::UpdateRequestMessage,::ECSSE::ExecuteStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_cache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_cache() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ECSSE::CacheRequestMessage, ::ECSSE::ExecuteStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ECSSE::CacheRequestMessage, ::ECSSE::ExecuteStatus>* streamer) {
                       return this->Streamedcache(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_cache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status cache(::grpc::ServerContext* /*context*/, const ::ECSSE::CacheRequestMessage* /*request*/, ::ECSSE::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedcache(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ECSSE::CacheRequestMessage,::ECSSE::ExecuteStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_setup<WithStreamedUnaryMethod_update<WithStreamedUnaryMethod_cache<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_search() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::ECSSE::SearchRequestMessage, ::ECSSE::SearchReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::ECSSE::SearchRequestMessage, ::ECSSE::SearchReply>* streamer) {
                       return this->Streamedsearch(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status search(::grpc::ServerContext* /*context*/, const ::ECSSE::SearchRequestMessage* /*request*/, ::grpc::ServerWriter< ::ECSSE::SearchReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedsearch(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::ECSSE::SearchRequestMessage,::ECSSE::SearchReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_search<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_setup<WithSplitStreamingMethod_search<WithStreamedUnaryMethod_update<WithStreamedUnaryMethod_cache<Service > > > > StreamedService;
};

}  // namespace ECSSE


#endif  // GRPC_ECSSE_2eproto__INCLUDED
